workflows:
  dr_mohamed_clinic_android:
    name: Dr Mohamed Clinic Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: default

    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Build Android App Bundle (release)
        script: |
          flutter build appbundle --release

      # لو حابب كمان APK (اختياري)
      - name: Build Android APK (release)
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/app/outputs/flutter-apk/app-release.apk

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - build/
