workflows:
  dr_mohamed_clinic_android:
    name: Dr Mohamed Clinic Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable

    scripts:
      - name: Create clean Flutter project
        script: |
          echo "Creating clean Flutter project in /tmp/app"
          flutter create -t app /tmp/app

      - name: Copy clinic app code into clean project
        script: |
          echo "Copying lib, pubspec, assets into clean flutter project"
          rm -rf /tmp/app/lib
          cp -R lib /tmp/app/lib

          cp pubspec.yaml /tmp/app/pubspec.yaml || true

          if [ -d assets ]; then
            rm -rf /tmp/app/assets
            cp -R assets /tmp/app/assets
          fi

          # لو google-services.json موجود في الريبو الأصلي
          if [ -f android/app/google-services.json ]; then
            cp android/app/google-services.json /tmp/app/android/app/google-services.json
          fi

      - name: Configure Android id, namespace, label & MainActivity
        script: |
          cd /tmp/app

          echo "Setting applicationId and namespace"
          sed -i.bak 's/applicationId ".*"/applicationId "com.dr.mohamedesmail.clinic"/' android/app/build.gradle || true
          sed -i.bak 's/namespace ".*"/namespace "com.dr.mohamedesmail.clinic"/' android/app/build.gradle || true

          echo "Updating AndroidManifest package and label"
          sed -i.bak 's/package="[^"]*"/package="com.dr.mohamedesmail.clinic"/' android/app/src/main/AndroidManifest.xml || true
          sed -i.bak 's/android:label="[^"]*"/android:label="Dr Mohamed clinic"/' android/app/src/main/AndroidManifest.xml || true

          echo "Fixing MainActivity for Kotlin"
          if [ -f android/app/src/main/kotlin/com/example/dr_mohamed_clinic/MainActivity.kt ]; then
            mkdir -p android/app/src/main/kotlin/com/dr/mohamedesmail/clinic
            mv android/app/src/main/kotlin/com/example/dr_mohamed_clinic/MainActivity.kt android/app/src/main/kotlin/com/dr/mohamedesmail/clinic/MainActivity.kt
          fi

          if [ -f android/app/src/main/kotlin/com/dr/mohamedesmail/clinic/MainActivity.kt ]; then
            sed -i.bak 's/^package .*/package com.dr.mohamedesmail.clinic/' android/app/src/main/kotlin/com/dr/mohamedesmail/clinic/MainActivity.kt
          fi

          echo "Fixing MainActivity for Java (if exists)"
          if [ -f android/app/src/main/java/com/example/dr_mohamed_clinic/MainActivity.java ]; then
            mkdir -p android/app/src/main/java/com/dr/mohamedesmail/clinic
            mv android/app/src/main/java/com/example/dr_mohamed_clinic/MainActivity.java android/app/src/main/java/com/dr/mohamedesmail/clinic/MainActivity.java
            sed -i.bak 's/^package .*/package com.dr.mohamedesmail.clinic;/' android/app/src/main/java/com/dr/mohamedesmail/clinic/MainActivity.java
          fi

      - name: Flutter pub get
        script: |
          cd /tmp/app
          flutter pub get

      - name: Build Android appbundle (release)
        script: |
          cd /tmp/app
          flutter build appbundle --release

      - name: Build Android apk (release)
        script: |
          cd /tmp/app
          flutter build apk --release

      - name: Copy build artifacts
        script: |
          cd /tmp/app
          ls -R build || true
          cp build/app/outputs/bundle/release/app-release.aab $CM_BUILD_DIR/app-release.aab || true
          cp build/app/outputs/flutter-apk/app-release.apk $CM_BUILD_DIR/app-release.apk || true

    artifacts:
      - app-release.aab
      - app-release.apk
